#!/bin/sh
#
# Reload sysctl parameters
#

case "$1" in
  start)
    echo "Reloading sysctl parameters..."
    sysctl -p
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    # Nothing to do on stop
    ;;
  restart)
    echo "Reloading sysctl parameters..."
    sysctl -p
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0