#!/bin/sh
### BEGIN INIT INFO
# Provides:          sysctl-reload
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Reload sysctl parameters
# Description:       Reload sysctl parameters from /etc/sysctl.conf
### END INIT INFO

case "$1" in
  start)
    echo "Reloading sysctl parameters..."
    sysctl -p
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    # Nothing to do on stop
    ;;
  restart)
    echo "Reloading sysctl parameters..."
    sysctl -p
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0